name: CI Ubuntu

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Cache OpenCV
      id: cache-opencv
      uses: actions/cache@v1
      with:
        path: ./opencv-install
        key: ${{ runner.os }}-opencvUb
        restore-keys: |
          ${{ runner.os }}-opencv

    - name: cmake configure without opencv
      if: steps.cache-opencv.outputs.cache-hit != 'true'
      run: cmake . -DCMAKE_BUILD_TYPE=Release
    - name: cmake configure with opencv
      if: steps.cache-opencv.outputs.cache-hit == 'true'
      run: cmake . -DOpenCV_DIR=opencv-install/ -DBUILD_OPENCV=OFF
    - name: ls
      run: ls opencv-install
